language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

 
 # 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "ytjojo"
- git config --global user.email "ytjojo@163.com"
# 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
#- npm install -g hexo-cli
install:
# 不用yarn的话这里改成 npm i 即可
- yarn
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ytjojo"
  - git config user.email "ytjojo@163.com"
  - git add --all .
  - git commit -m "Update docs"
  - git push --force --quiet "https://$GH_TOKEN@$GH_REF" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com:ytjojo/ytjojo.github.io.git